module.exports = {
  content: ["src/**/*.{tsx,ts,js,jsx}"],
  theme: {
    fontFamily: {
      sans: "Roboto",
    },
    extend: {
      colors: {
        "card-bg": "#3b4252",
        "page-bg": "#2e3440",
        compositr: "#f24fff",

        nord0: "#2E3440",
        nord1: "#3B4252",
        nord2: "#434C5E",
        nord3: "#4C566A",
        nord4: "#D8DEE9",
        nord5: "#E5E9F0",
        nord6: "#ECEFF4",
        nord7: "#8FBCBB",
        nord8: "#88C0D0",
        nord9: "#81A1C1",
        nord10: "#5E81AC",
        nord11: "#BF616A",
        nord12: "#D08770",
        nord13: "#EBCB8B",
        nord14: "#A3BE8C",
        nord15: "#B48EAD",
      },
      typography: ({ theme }) => ({
        white: {
          css: {
            "--tw-prose-body": "#eceff4",
            "--tw-prose-headings": "#eceff4",
            "--tw-prose-lead": "#eceff4",
            "--tw-prose-links": "#eceff4",
            "--tw-prose-bold": "#eceff4",
            "--tw-prose-counters": "#eceff4",
            "--tw-prose-bullets": "#eceff4",
            "--tw-prose-hr": "#eceff4",
            "--tw-prose-quotes": "#eceff4",
            "--tw-prose-quote-borders": "#eceff4",
            "--tw-prose-captions": "#eceff4",
            "--tw-prose-code": "#eceff4",
            "--tw-prose-pre-code": "#eceff4",
            "--tw-prose-pre-bg": "#eceff4",
            "--tw-prose-th-borders": "#eceff4",
            "--tw-prose-td-borders": "#eceff4",
            "--tw-prose-invert-body": "#eceff4",
            "--tw-prose-invert-headings": "#eceff4",
            "--tw-prose-invert-lead": "#eceff4",
            "--tw-prose-invert-links": "#eceff4",
            "--tw-prose-invert-bold": "#eceff4",
            "--tw-prose-invert-counters": "#eceff4",
            "--tw-prose-invert-bullets": "#eceff4",
            "--tw-prose-invert-hr": "#eceff4",
            "--tw-prose-invert-quotes": "#eceff4",
            "--tw-prose-invert-quote-borders": "#eceff4",
            "--tw-prose-invert-captions": "#eceff4",
            "--tw-prose-invert-code": "#eceff4",
            "--tw-prose-invert-pre-code": "#eceff4",
            "--tw-prose-invert-pre-bg": "rgb(0 0 0 / 50%)",
            "--tw-prose-invert-th-borders": "#eceff4",
            "--tw-prose-invert-td-borders": "#eceff4",
          },
        },
      }),
    },
  },
  plugins: [require("@tailwindcss/typography"), require("@tailwindcss/forms")],
};
